export const projectData = [
  {
    image: "/assets/Shelter.jpg",
    title: "Shelter",
    githubLink: "https://github.com/youneshajizde/shelter-app",
    appUrl: "shelter.vercel.app",
    desc: "An App where you can find proper houses while being able to buy related products",
    highlights: [
      "Ability to reserve houses",
      "Ability to Buy products",
      "User Dashboard",
    ],
    stacks: [
      "Next.js",
      "React",
      "Tailwind",
      "Framer motion",
      "Supabase",
      "Zustand",
    ],
    isLive: true,
  },
  {
    image: "/assets/Evcon.jpg",
    title: "EvCon",
    githubLink: "https://github.com/youneshajizde/evcon-app",
    appUrl: "evcon.vercel.app",
    desc: "Website where you are able to reserve for seminars and events as well as handling them in your dashboard and uploading events",
    highlights: [
      "Ability to get tickets",
      "Ability to upload your events",
      "User Dashboard",
      "Admin Dashboard",
    ],
    stacks: [
      "Next.js",
      "React",
      "Tailwind",
      "Framer motion",
      "Supabase",
      "Zustand",
    ],
    isLive: true,
  },
  {
    image: "/assets/CareSync.jpg",
    title: "CareSync",
    githubLink: "https://github.com/youneshajizde/careSync-baas-appwrite",
    appUrl: "https://care-sync-appwrite.vercel.app/",
    desc: "An app where user can fill appointment for doctors with admin dashboard to manage patients' appointments",
    highlights: [
      "Ability to fill appointments",
      "handling appointments",
      "admin Dashboard",
    ],
    stacks: ["Next.js", "React", "Tailwind", "Appwrite", "Context api"],
    isLive: true,
  },

  {
    image: "/assets/Bazaaro.jpg",
    title: "Bazaaro",
    githubLink: "https://github.com/youneshajizde/bazaaro-app",
    appUrl: "",
    desc: "A Clean and beautiful e-commerce website for buying products",
    highlights: [
      "Cart and buying process",
      "Using video for showcasing some products",
    ],
    stacks: ["Next.js", "React", "Tailwind", "Appwrite", "Context api"],
    isLive: false,
  },
];
